#!/usr/bin/env bash
set -eEuo pipefail
test -z "${DEBUG:-}" || set -x

workdir="${BASH_SOURCE[0]%/*}"

release="openebs"
chart="${workdir}"
export namespace="openebs-system"
args=(--namespace "$namespace")
cmd=""
cmds=()

while [[ $# -gt 0 ]]; do
  case "$1" in
  -*)
    args+=("$1")
    ;;
  *)
    if test "${#cmds[@]}" -gt 0; then
      args+=("$1")
    else
      cmd="$1"
    fi
    ;;
  esac
  shift
done

if test "${cmd}" == install ; then
  cmd="upgrade"
fi
cmds=("${cmd}")

case "${cmd}" in
template | install | upgrade)
  args+=("${release}" "${chart}")
  ;;
esac

if test "${cmd}" == upgrade ;then
  args+=(--install)
fi

case "${cmd}" in
install | upgrade)
  kubectl apply -f "${chart}/namespace.yaml"
  ;;
esac

if test "${cmd}" == "upgrade"; then
  # --detailed-exitcode
  helm diff "${cmds[@]}" "${args[@]}"
fi

helm "${cmds[@]}" "${args[@]}"
