rook-ceph-cluster:
  cephClusterSpec:
    mgr:
      count: 3
    mon:
      count: 3
    resources:
      mgr:
        limits:
          memory: "1Gi"
        requests:
          #cpu: "500m"
          cpu: 50m
          #memory: "512Mi"
          memory: "512Mi"
      mon:
        limits:
          #memory: "2Gi"
          memory: 2Gi
        requests:
          #cpu: "1000m"
          cpu: 100m
          #memory: "1Gi"
          memory: "1Gi"
      osd:
        limits:
          #memory: "4Gi"
          memory: 4Gi
        requests:
          #cpu: "1000m"
          cpu: 100m
          #memory: "4Gi"
          memory: "4Gi"
      prepareosd:
        # limits: It is not recommended to set limits on the OSD prepare job
        #         since it's a one-time burst for memory that must be allowed to
        #         complete without an OOM kill.  Note however that if a k8s
        #         limitRange guardrail is defined external to Rook, the lack of
        #         a limit here may result in a sync failure, in which case a
        #         limit should be added.  1200Mi may suffice for up to 15Ti
        #         OSDs ; for larger devices 2Gi may be required.
        #         cf. https://github.com/rook/rook/pull/11103
        requests:
          #cpu: "500m"
          cpu: 50m
          memory: "50Mi"
      mgr-sidecar:
        limits:
          memory: "100Mi"
        requests:
          #cpu: "100m"
          cpu: "10m"
          memory: "40Mi"
      crashcollector:
        limits:
          memory: "60Mi"
        requests:
          #cpu: "100m"
          cpu: "10m"
          memory: "60Mi"
      logcollector:
        limits:
          memory: "1Gi"
        requests:
          #cpu: "100m"
          cpu: "10m"
          memory: "100Mi"
      cleanup:
        limits:
          memory: "1Gi"
        requests:
          #cpu: "500m"
          cpu: "50m"
          memory: "100Mi"
      exporter:
        limits:
          memory: "128Mi"
        requests:
          #cpu: "50m"
          cpu: "5m"
          memory: "50Mi"
