namespace: nix-system

resources:
  - daemonset.yaml

generatorOptions:
  disableNameSuffixHash: false

images:
  - name: docker.io/nixos/nix
    newTag: 2.23.1

configMapGenerator:
  - name: nix-disks-src
    files:
      - nix/.envrc
      - nix/.gitignore
      - nix/local-storage.disko.lib.nix
      - nix/container-entrypoint.sh
      - nix/disks.nix
      - nix/flake.lock
      - nix/flake.nix
      - nix/handle-drives.sh
