kubelet-csr-approver:
  ignoreNonSystemNode: true
  # TODO: possibly resolves something else, so it doesn't match CSR IPs
  bypassDnsResolution: true
  allowedDnsNames: 1
  providerIpPrefixes:
  - 192.168.41.0/24
  - fd31:e17c:f07f:1::/64
  maxExpirationSeconds: 86400

  leaderElection: true
  replicas: 2
