namespace: nix-system

resources:
  - daemonset.yaml

configMapGenerator:
  - name: nix-disks-src
    files:
      - nix/.envrc
      - nix/.gitignore
      - nix/local-storage.disko.lib.nix
      - nix/container-entrypoint.sh
      - nix/disks.nix
      - nix/flake.lock
      - nix/flake.nix
      - nix/handle-drives.sh
