openebs:
  openebs-crds:
    csi:
      volumeSnapshots:
        enabled: false # installed separately
        keep: false # installed separately
  engines:
    local:
      lvm:
        enabled: false
    replicated:
      mayastor:
        enabled: false
  zfs-localpv:
    zfsNode:
      encrKeysDir: /var/lib/internal/openebs/zfs-localpv/keys
