namespace: nix-system

resources:
  - namespace.yaml
  - nix-daemon.ds.yaml

images:
  - name: docker.io/nixos/nix
    newTag: 2.23.1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nix-files
    files:
      - nix.conf
  - name: nix-client-env
    envs:
      - nix-client.env
  - name: nix-daemon-env
    envs:
      - nix-daemon.env

secretGenerator:
  - name: nix-files
  #    files:
  #      - nix.sensitive.conf
  - name: nix-client-env
  - name: nix-daemon-env
