kubelet-csr-approver:
  ignoreNonSystemNode: true
  # TODO: probably resolves something else, because it doesn't match CSR IPs
  bypassDnsResolution: true
  allowedDnsNames: 1
  providerIpPrefixes:
  - 10.92.0.0/16
  - fd12:ed4e:366d:eb17::/64
  maxExpirationSeconds: 86400

  leaderElection: true
  replicas: 2
