rook-ceph-cluster:
  operatorNamespace: rook-system
  clusterName: pic-rook
  toolbox:
    enabled: true
  monitoring:
    enabled: false
  dashboard:
    enabled: true

  cephClusterSpec:
    dataDirHostPath: /var/lib/internal/rook/pic-rook

    mon:
      count: 3
      volumeClaimTemplate:
        spec:
          storageClassName: zfs
          resources:
            requests:
              storage: 10Gi

    storage:
      useAllNodes: true
      useAllDevices: false
      config:
        osdsPerDevice: "1"
        encryptedDevice: "true"
      storageClassDeviceSets:
        - name: rook-ceph-hdd
          count: 3
          portable: true
          encrypted: true
          config:
            deviceClass: hdd
          volumeClaimTemplates:
            - metadata:
                labels:
                  rook.storage.kdn.im/device-class: hdd
              spec:
                storageClassName: manual-rook-ceph-cluster
                resources:
                  requests:
                    storage: 4T
                volumeMode: Block
                accessModes:
                  - ReadWriteOnce
        - name: rook-ceph-ssd
          count: 3
          portable: true
          encrypted: true
          config:
            deviceClass: ssd
          volumeClaimTemplates:
            - metadata:
                labels:
                  rook.storage.kdn.im/device-class: ssd
              spec:
                storageClassName: manual-rook-ceph-cluster
                resources:
                  requests:
                    storage: 1T
                volumeMode: Block
                accessModes:
                  - ReadWriteOnce

  cephBlockPools: []
  cephFileSystems: []
  cephObjectStores: []
