namespace: nix-system

resources:
  - namespace.yaml
  - nix-client.ds.yaml
  - nix-daemon.ds.yaml

images:
  - name: docker.io/nixos/nix
    newTag: 2.21.1

configMapGenerator:
  - name: nix-files
    files:
      - nix.conf
  - name: nix-client-env
    envs:
      - nix-client.env
  - name: nix-daemon-env
    envs:
      - nix-daemon.env

secretGenerator:
  - name: nix-files
    files:
      - nix.sensitive.conf
  - name: nix-client-env
  - name: nix-daemon-env