apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdd-ironwolf-pro-4tb-0
  labels:
    storage.kdn.im/device-class: hdd
  annotations:
    storage.kdn.im/descrition: "HDD - 4 TB - Seagate Ironwolf Pro"
    storage.kdn.im/notes: ""
spec:
  storageClassName: manual-rook-ceph-cluster
  capacity:
    storage: '4000787030016'
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/disk/by-id/wwn-0x5000c500e0cd37a6
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pwet
